version: '3'
services:
  mysql:
    image: mysql
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: super_secret_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql
    container_name: mysql_server

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: super_secret_password
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
  
  web:
    build: ./webapp
    restart: always
    ports:
     - '81:81'
    volumes:
      - ./webapp:/app
    container_name: babyapp
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
